name: Build DLL

on:
  workflow_dispatch: # lets you run it manually

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Get your repo's code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build the DLL (change 'source.cpp' if needed)
      - name: Build DLL
        run: |
          cl /LD /EHsc source.cpp /Fe:MyLibrary.dll

      # 3. Save DLL so you can download it
      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: MyLibrary
          path: MyLibrary.dll
